# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
decode_beta <- function(encoded) {
    .Call(`_scrcpp_decode_beta`, encoded)
}

#' @export
decode_cov <- function(encoded) {
    .Call(`_scrcpp_decode_cov`, encoded)
}

#' Vector Decoder
#' This function unpacks the encoded \eqn{\beta} and coverage values from the
#' encoded column of a methylation matrix.
#' @param encoded An encoded sample column from a data.table methylation matrix of CpG loci by samples
#' @param measure The required decoded value: 1 for beta, 2 for coverage and 3 for M
#' @export
vdecoder <- function(encoded, measure) {
    .Call(`_scrcpp_vdecoder`, encoded, measure)
}

#' Double Vector Decoder
#' This function unpacks the encoded \eqn{\beta} and coverage values from the
#' encoded column of a methylation matrix.
#' @param encoded An encoded sample column from a data.table methylation matrix of CpG loci by samples
#' @param measure The required decoded value: 1 for beta, 2 for coverage and 3 for M
#' @export
vdouble_decoder <- function(encoded, measure) {
    .Call(`_scrcpp_vdouble_decoder`, encoded, measure)
}

#' @export
vencoder <- function(beta_col, cov_col) {
    .Call(`_scrcpp_vencoder`, beta_col, cov_col)
}

